/*
    Open1560 - An Open Source Re-Implementation of Midtown Madness 1 Beta
    Copyright (C) 2020 Brick

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

#include "dx9remixwet.h"

#include "agi/vertex.h"
#include "agiworld/skyenv.h"
#include "vector7/matrix34.h"

#include "dx9remix.h"
#include "dx9remixapi.h"

#include "dx9_windows.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <memory>
#include <mutex>

// std::fopen is deprecated by MSVC and this build is /WX. Writing two texture files next to the game
// is not the unsafety the deprecation is aimed at - same treatment and reasoning as dx9config.cpp.
#pragma warning(disable : 4996)

define_dummy_symbol(agidx9_dx9remixwet);

// HOW IT WORKS
//
// 1. The wet mask. A tileable pair of textures, generated by the game from noise the first time a
//    race needs them and cached on disk (Open1560_RemixWet/), one pair per wetness level:
//
//      albedo+opacity  - near-black water in puddles, a dark film where the road is only damp, and
//                        the mask itself in alpha: which parts of the road are wet, and how wet.
//      roughness       - mirror-smooth in puddles, part-way down where damp.
//
//    Remix blends a decal's albedo, roughness and normal into the surface under it by the decal's
//    opacity, so opacity 0 leaves the road as it was and opacity 1 in a puddle turns it into water.
//    The level is baked into the textures rather than applied as a material constant because Remix
//    ignores the opacity constant once the albedo texture has an alpha channel (the texture's alpha
//    REPLACES it - opaque_surface_material_interaction.slangh), and the weather is fixed for a whole
//    race here, so one pair per race is all it costs.
//
//    Two noise fields, both periodic so the tile repeats without a seam: a low-frequency one for
//    where the puddles pool, thresholded by coverage, and a finer one for the grain of damp tarmac
//    between them. Puddles grow as the weather gets wetter - the threshold drops with the level -
//    rather than fading uniformly, which is how a road actually fills.
//
// 2. The geometry. Road and ground reach the hardware path through agiMeshSet::DrawLitEnv, which
//    flags the draw (agiNativeGroundDraw), and MeshWorld hands each one here with its model-space
//    vertices and world matrix. The first time a piece is seen this race, its upward-facing
//    triangles - the road surface, not kerb faces or walls - become one Remix API mesh:
//
//      - positions in WORLD space, lifted 5 mm clear of the road, drawn with an identity transform;
//      - texture coordinates from world X and Z over -remixwettile, so the puddles stay where they
//        are on the ground, continuous from one road piece to the next, instead of following each
//        piece's own UV layout.
//
//    A piece is keyed by a hash of its world matrix, positions and indices - the same things that
//    make it the same piece to Remix - so cell geometry that is paged out and back in finds its
//    mesh again. Creation is capped per frame so a cell streaming in costs a few frames of bridge
//    traffic rather than one hitch.
//
// 3. Every frame, each piece the game draws gets its twin drawn with it, as DECAL_STATIC, from
//    inside the draw that submitted the road - so the layer is in the frame's scene before anything
//    can trigger Remix's path trace (see agiDX9Pipeline::SendRemixFrame).
//
// 4. A little extra gloss everywhere: rtx.legacyMaterial.roughnessConstant, the roughness Remix
//    gives every game texture without a replacement, is lowered in proportion to the wetness - cars
//    and buildings are wet too. Put back when the race ends.
//
// What it does not do: know what is under cover. A road under an overpass is as wet as one in the
// open. And the pattern is one tile, repeated - large enough (64 m by default) that it reads as
// puddles rather than a grid.

static mem::cmd_param PARAM_remixwet {"remixwet", "RTX Remix wet roads in rain (Remix API)"};

// Wetness per weather, 0..1. The game's weather is fixed for a race, so these are the whole story.
static mem::cmd_param PARAM_remixwet_clear {"remixwetclear", "Road wetness in clear weather, 0-1"};
static mem::cmd_param PARAM_remixwet_fog {"remixwetfog", "Road wetness in fog, 0-1"};
static mem::cmd_param PARAM_remixwet_rain {"remixwetrain", "Road wetness in rain, 0-1"};
static mem::cmd_param PARAM_remixwet_snow {"remixwetsnow", "Road wetness in snow, 0-1"};

static mem::cmd_param PARAM_remixwet_tile {"remixwettile", "Size of the repeating puddle pattern, in world units"};
static mem::cmd_param PARAM_remixwet_coverage {"remixwetcoverage", "Share of the road under puddles at full wetness"};
static mem::cmd_param PARAM_remixwet_seed {"remixwetseed", "Seed of the puddle pattern"};
static mem::cmd_param PARAM_remixwet_res {"remixwetres", "Resolution of the puddle textures (power of two)"};
static mem::cmd_param PARAM_remixwet_puddle_rough {"remixwetpuddleroughness", "Roughness of standing water"};
static mem::cmd_param PARAM_remixwet_damp_rough {"remixwetdamproughness", "Roughness of damp road"};
static mem::cmd_param PARAM_remixwet_gloss {
    "remixwetgloss", "rtx.legacyMaterial.roughnessConstant at full wetness (0 leaves it alone)"};
static mem::cmd_param PARAM_remixwet_dry_rough {
    "remixwetdryroughness", "rtx.legacyMaterial.roughnessConstant to restore when dry"};
static mem::cmd_param PARAM_remixwet_slope {
    "remixwetslope", "Minimum upward normal (0-1) for a surface to take puddles"};
static mem::cmd_param PARAM_remixwet_max_new {"remixwetmaxnew", "Most road meshes created per frame"};

namespace
{
    // "O1WE" in the top bits keeps our hashes recognisable in a capture and clear of 0.
    constexpr u64 kMeshTag = 0x4F31574500000000ull;
    constexpr u64 kMaterialTag = 0x4F3157454D000000ull;

    constexpr u32 kTableSize = 8192;
    static_assert((kTableSize & (kTableSize - 1)) == 0, "kTableSize must be a power of two");
    constexpr u32 kMaxEntries = kTableSize / 2;

    // Largest road piece taken. The biggest cell meshes are a few thousand vertices; anything past
    // this is left dry rather than given a stack-sized buffer.
    constexpr u32 kMaxSourceVertices = 8192;
    constexpr u32 kMaxSourceIndices = 3 * 8192;

    enum class EntryState : u8
    {
        Free,
        Mesh,  // has a Remix mesh
        Empty, // nothing upward-facing, or too large: nothing to draw, but do not look again
    };

    struct Entry
    {
        u64 Key;
        remixapi_MeshHandle Handle;
        u32 LastFrame;
        EntryState State;
    };

    enum class RaceState : u8
    {
        Unknown, // not decided yet this race
        Off,     // dry, switched off, or no API
        On,
    };

    struct Stats
    {
        u32 Created;
        u32 Drawn;
        u32 Skipped;
    };

    // Fixed storage, for the reason dx9remix.cpp gives: the engine resets its memory arena between
    // races, and this outlives any one of them.
    Entry s_table[kTableSize] {};
    u32 s_entries = 0;

    remixapi_HardcodedVertex s_out_vertices[kMaxSourceVertices] {};
    u32 s_out_indices[kMaxSourceIndices] {};
    u32 s_remap[kMaxSourceVertices] {};

    std::mutex s_lock;

    RaceState s_race = RaceState::Unknown;
    f32 s_level = 0.0f;
    remixapi_MaterialHandle s_material = nullptr;
    bool s_gloss_applied = false;

    u32 s_frame = 1;
    u32 s_created_this_frame = 0;

    wchar_t s_albedo_path[MAX_PATH] {};
    wchar_t s_roughness_path[MAX_PATH] {};

    Stats s_stats {};
} // namespace

static u64 Fnv(const void* data, usize size, u64 hash)
{
    const u8* bytes = static_cast<const u8*>(data);

    for (usize i = 0; i < size; ++i)
    {
        hash ^= bytes[i];
        hash *= 0x100000001B3ull;
    }

    return hash;
}

// --- The noise ----------------------------------------------------------------------------------

static u32 HashLattice(u32 x, u32 y, u32 seed)
{
    u32 h = (x * 0x8DA6B343u) ^ (y * 0xD8163841u) ^ (seed * 0xCB1AB31Fu);
    h ^= h >> 13;
    h *= 0x5BD1E995u;
    h ^= h >> 15;
    return h;
}

// Value noise on a lattice `period` cells across, wrapping at the edge, so the texture tiles.
static f32 PeriodicNoise(f32 u, f32 v, u32 period, u32 seed)
{
    const f32 x = u * static_cast<f32>(period);
    const f32 y = v * static_cast<f32>(period);

    const f32 fx = std::floor(x);
    const f32 fy = std::floor(y);

    const u32 x0 = static_cast<u32>(fx) % period;
    const u32 y0 = static_cast<u32>(fy) % period;
    const u32 x1 = (x0 + 1) % period;
    const u32 y1 = (y0 + 1) % period;

    auto fade = [](f32 t) { return t * t * t * (t * (t * 6.0f - 15.0f) + 10.0f); };

    const f32 tx = fade(x - fx);
    const f32 ty = fade(y - fy);

    auto value = [seed](u32 lx, u32 ly) {
        return static_cast<f32>(HashLattice(lx, ly, seed) >> 8) * (1.0f / 16777216.0f);
    };

    const f32 a = value(x0, y0) + (value(x1, y0) - value(x0, y0)) * tx;
    const f32 b = value(x0, y1) + (value(x1, y1) - value(x0, y1)) * tx;

    return a + (b - a) * ty;
}

static f32 PeriodicFbm(f32 u, f32 v, u32 base_period, u32 octaves, u32 seed)
{
    f32 sum = 0.0f;
    f32 amplitude = 1.0f;
    f32 total = 0.0f;
    u32 period = base_period;

    for (u32 i = 0; i < octaves; ++i)
    {
        sum += PeriodicNoise(u, v, period, seed + (i * 101u)) * amplitude;
        total += amplitude;
        amplitude *= 0.5f;
        period *= 2;
    }

    return sum / total;
}

static f32 SmoothStep(f32 edge0, f32 edge1, f32 x)
{
    const f32 t = std::clamp((x - edge0) / (edge1 - edge0), 0.0f, 1.0f);
    return t * t * (3.0f - 2.0f * t);
}

static u8 ToByte(f32 value)
{
    return static_cast<u8>(std::clamp(value, 0.0f, 1.0f) * 255.0f + 0.5f);
}

static f32 LinearToSrgb(f32 linear)
{
    return (linear <= 0.0031308f) ? (linear * 12.92f) : (1.055f * std::pow(linear, 1.0f / 2.4f) - 0.055f);
}

// --- DDS ----------------------------------------------------------------------------------------

// A DX10-header DDS with a full box-filtered mip chain. Uncompressed RGBA8: the textures are
// generated once and read by Remix's own loader, so there is nothing to gain from compressing them
// here and a quality loss in the smooth roughness ramps if we did.
static bool WriteDds(const char* file_name, const u8* pixels, u32 size, bool srgb)
{
    std::FILE* file = std::fopen(file_name, "wb");

    if (!file)
        return false;

    u32 mips = 1;

    while ((size >> mips) != 0)
        ++mips;

    u32 header[32] {};
    header[0] = 0x20534444; // "DDS "
    header[1] = 124;
    header[2] = 0x1 | 0x2 | 0x4 | 0x8 | 0x1000 | 0x20000; // CAPS HEIGHT WIDTH PITCH PIXELFORMAT MIPMAPCOUNT
    header[3] = size;
    header[4] = size;
    header[5] = size * 4;
    header[7] = mips;
    header[19] = 32;                      // pixel format size
    header[20] = 0x4;                     // DDPF_FOURCC
    header[21] = 0x30315844;              // "DX10"
    header[27] = 0x1000 | 0x400000 | 0x8; // TEXTURE MIPMAP COMPLEX

    const u32 dx10[5] {srgb ? 29u : 28u, 3u, 0u, 1u, 0u}; // R8G8B8A8_UNORM(_SRGB), TEXTURE2D

    std::fwrite(header, sizeof(header), 1, file);
    std::fwrite(dx10, sizeof(dx10), 1, file);

    std::unique_ptr<u8[]> level(new u8[static_cast<usize>(size) * size * 4]);
    std::memcpy(level.get(), pixels, static_cast<usize>(size) * size * 4);

    for (u32 mip = 0, extent = size; mip < mips; ++mip, extent = std::max<u32>(extent / 2, 1))
    {
        std::fwrite(level.get(), static_cast<usize>(extent) * extent * 4, 1, file);

        if (extent == 1)
            break;

        // In place: each output texel reads four inputs that no earlier output has overwritten.
        const u32 half = extent / 2;

        for (u32 y = 0; y < half; ++y)
        {
            for (u32 x = 0; x < half; ++x)
            {
                for (u32 c = 0; c < 4; ++c)
                {
                    const u32 sum = level[((2 * y) * extent + (2 * x)) * 4 + c] +
                        level[((2 * y) * extent + (2 * x + 1)) * 4 + c] +
                        level[((2 * y + 1) * extent + (2 * x)) * 4 + c] +
                        level[((2 * y + 1) * extent + (2 * x + 1)) * 4 + c];

                    level[(y * half + x) * 4 + c] = static_cast<u8>((sum + 2) / 4);
                }
            }
        }
    }

    const bool ok = std::ferror(file) == 0;
    std::fclose(file);

    return ok;
}

static bool FileExists(const char* file_name)
{
    std::FILE* file = std::fopen(file_name, "rb");

    if (!file)
        return false;

    std::fclose(file);
    return true;
}

// Generates (or finds) this level's texture pair and fills s_albedo_path/s_roughness_path.
static bool PrepareTextures(f32 level)
{
    const u32 requested = static_cast<u32>(std::clamp(PARAM_remixwet_res.get_or(1024), 64, 4096));
    u32 size = 64;

    while ((size * 2) <= requested)
        size *= 2;

    const f32 coverage = std::clamp(PARAM_remixwet_coverage.get_or(0.2f), 0.0f, 1.0f);
    const u32 seed = static_cast<u32>(PARAM_remixwet_seed.get_or(1));
    const f32 puddle_rough = std::clamp(PARAM_remixwet_puddle_rough.get_or(0.03f), 0.0f, 1.0f);
    const f32 damp_rough = std::clamp(PARAM_remixwet_damp_rough.get_or(0.28f), 0.0f, 1.0f);

    // Everything that changes the pixels names the files, so a change of setting regenerates them and
    // an unchanged one reuses what is on disk. The trailing constant is the generator's version.
    u64 key = 0xCBF29CE484222325ull;
    key = Fnv(&level, sizeof(level), key);
    key = Fnv(&size, sizeof(size), key);
    key = Fnv(&coverage, sizeof(coverage), key);
    key = Fnv(&seed, sizeof(seed), key);
    key = Fnv(&puddle_rough, sizeof(puddle_rough), key);
    key = Fnv(&damp_rough, sizeof(damp_rough), key);
    const u32 version = 2;
    key = Fnv(&version, sizeof(version), key);

    char albedo_name[MAX_PATH];
    char roughness_name[MAX_PATH];
    std::snprintf(albedo_name, sizeof(albedo_name), "Open1560_RemixWet\\wet_albedo_%08X.dds", static_cast<u32>(key));
    std::snprintf(
        roughness_name, sizeof(roughness_name), "Open1560_RemixWet\\wet_rough_%08X.dds", static_cast<u32>(key));

    if (!FileExists(albedo_name) || !FileExists(roughness_name))
    {
        CreateDirectoryA("Open1560_RemixWet", nullptr);

        std::unique_ptr<u8[]> albedo(new u8[static_cast<usize>(size) * size * 4]);
        std::unique_ptr<u8[]> roughness(new u8[static_cast<usize>(size) * size * 4]);
        std::unique_ptr<f32[]> pools(new f32[static_cast<usize>(size) * size]);

        // Where water pools: a low-frequency field, domain-warped - its coordinates bent by a second
        // field - so the puddles come out as irregular, elongated shapes rather than round blobs on a
        // visible lattice. Both fields are periodic and the warp is added, not composed, so the
        // result still tiles without a seam.
        u32 histogram[1024] {};

        for (u32 y = 0; y < size; ++y)
        {
            const f32 v = (static_cast<f32>(y) + 0.5f) / static_cast<f32>(size);

            for (u32 x = 0; x < size; ++x)
            {
                const f32 u = (static_cast<f32>(x) + 0.5f) / static_cast<f32>(size);

                const f32 wu = u + 0.12f * (PeriodicFbm(u, v, 6, 3, seed + 31u) - 0.5f);
                const f32 wv = v + 0.12f * (PeriodicFbm(u, v, 6, 3, seed + 57u) - 0.5f);

                // Wrapped back into [0,1): the noise wraps anyway, this only keeps the floor() positive.
                const f32 pool = PeriodicFbm(wu - std::floor(wu), wv - std::floor(wv), 8, 4, seed);

                pools[static_cast<usize>(y) * size + x] = pool;
                ++histogram[std::min(static_cast<u32>(pool * 1024.0f), 1023u)];
            }
        }

        // Puddles take the highest `coverage * level` share of the pool field, exactly: the threshold is
        // read off the field's own distribution rather than guessed from the noise's nominal range. It
        // falls as the road gets wetter, so puddles grow from their deepest points outward instead of
        // fading in everywhere at once.
        const f32 effective = coverage * level;
        f32 threshold = 1.0f;

        {
            const u64 wanted = static_cast<u64>(static_cast<f64>(effective) * size * size);
            u64 above = 0;

            for (i32 bin = 1023; bin >= 0; --bin)
            {
                above += histogram[bin];

                if (above >= wanted)
                {
                    threshold = static_cast<f32>(bin) / 1024.0f;
                    break;
                }
            }

            if (wanted == 0)
                threshold = 1.1f;
        }

        // Colours in linear terms. Water over asphalt is close to black; a damp film is a darkening.
        constexpr f32 kPuddleAlbedo[3] {0.012f, 0.015f, 0.018f};
        constexpr f32 kDampAlbedo[3] {0.03f, 0.03f, 0.03f};

        for (u32 y = 0; y < size; ++y)
        {
            const f32 v = (static_cast<f32>(y) + 0.5f) / static_cast<f32>(size);

            for (u32 x = 0; x < size; ++x)
            {
                const f32 u = (static_cast<f32>(x) + 0.5f) / static_cast<f32>(size);

                const f32 pool = pools[static_cast<usize>(y) * size + x];
                const f32 grain = PeriodicFbm(u, v, 32, 4, seed + 7919u);

                const f32 puddle = SmoothStep(threshold - 0.015f, threshold + 0.015f, pool);

                // Damp everywhere it is wet at all, heavier toward the puddles' edges and in the grain.
                const f32 rim = SmoothStep(threshold - 0.06f, threshold, pool);
                const f32 damp = level * std::max(0.55f + 0.45f * grain, rim);

                const f32 opacity = std::clamp(std::max(puddle * 0.94f, damp * 0.42f), 0.0f, 1.0f);

                u8* a = &albedo[(static_cast<usize>(y) * size + x) * 4];
                u8* r = &roughness[(static_cast<usize>(y) * size + x) * 4];

                for (u32 c = 0; c < 3; ++c)
                    a[c] = ToByte(LinearToSrgb(kDampAlbedo[c] + (kPuddleAlbedo[c] - kDampAlbedo[c]) * puddle));

                a[3] = ToByte(opacity);

                const u8 rough = ToByte(damp_rough + (puddle_rough - damp_rough) * puddle);
                r[0] = r[1] = r[2] = rough;
                r[3] = 255;
            }
        }

        if (!WriteDds(albedo_name, albedo.get(), size, true) || !WriteDds(roughness_name, roughness.get(), size, false))
        {
            Warningf("Remix wet roads: could not write the puddle textures to Open1560_RemixWet\\; wet roads are off.");
            return false;
        }

        Displayf("Remix wet roads: generated %ux%u puddle textures for wetness %.2f", size, size, level);
    }

    // Remix loads the files itself, from the bridge server's process, so it needs a path that does not
    // depend on anyone's working directory.
    wchar_t wide[MAX_PATH];

    MultiByteToWideChar(CP_ACP, 0, albedo_name, -1, wide, MAX_PATH);
    GetFullPathNameW(wide, MAX_PATH, s_albedo_path, nullptr);

    MultiByteToWideChar(CP_ACP, 0, roughness_name, -1, wide, MAX_PATH);
    GetFullPathNameW(wide, MAX_PATH, s_roughness_path, nullptr);

    return true;
}

static bool CreateWetMaterial(const agiDX9RemixSceneApi& api, f32 level)
{
    remixapi_MaterialInfoOpaqueEXT opaque {};
    opaque.sType = REMIXAPI_STRUCT_TYPE_MATERIAL_INFO_OPAQUE_EXT;
    opaque.pNext = nullptr;
    opaque.roughnessTexture = s_roughness_path;
    opaque.metallicTexture = L"";
    opaque.anisotropy = 0.0f;
    opaque.albedoConstant = {1.0f, 1.0f, 1.0f};
    opaque.opacityConstant = 1.0f;
    opaque.roughnessConstant = 0.3f;
    opaque.metallicConstant = 0.0f;
    opaque.thinFilmThickness_hasvalue = 0;
    opaque.thinFilmThickness_value = 0.0f;
    opaque.alphaIsThinFilmThickness = 0;
    opaque.heightTexture = L"";
    opaque.displaceIn = 0.0f;
    opaque.useDrawCallAlphaState = 0;

    // Alpha blended by the texture's alpha - the wet mask - and never alpha tested away.
    opaque.blendType_hasvalue = 1;
    opaque.blendType_value = 0; // BlendType::kAlpha
    opaque.invertedBlend = 0;
    opaque.alphaTestType = 7; // AlphaTestType::kAlways
    opaque.alphaReferenceValue = 0;
    opaque.displaceOut = 0.0f;

    remixapi_MaterialInfo info {};
    info.sType = REMIXAPI_STRUCT_TYPE_MATERIAL_INFO;
    info.pNext = &opaque;
    info.hash = kMaterialTag | (Fnv(s_albedo_path, sizeof(s_albedo_path), 0xCBF29CE484222325ull) & 0xFFFFFFull);
    info.albedoTexture = s_albedo_path;
    info.normalTexture = L"";
    info.tangentTexture = L"";
    info.emissiveTexture = L"";
    info.emissiveIntensity = 0.0f;
    info.emissiveColorConstant = {0.0f, 0.0f, 0.0f};
    info.spriteSheetRow = 1;
    info.spriteSheetCol = 1;
    info.spriteSheetFps = 0;
    info.filterMode = 1; // linear
    info.wrapModeU = 1;  // repeat - the pattern tiles across the city
    info.wrapModeV = 1;

    s_material = nullptr;

    if ((api.CreateMaterial(&info, &s_material) != REMIXAPI_ERROR_CODE_SUCCESS) || !s_material)
    {
        Warningf("Remix wet roads: CreateMaterial failed; wet roads are off.");
        return false;
    }

    Displayf("Remix wet roads: wetness %.2f", level);
    return true;
}

static f32 WetnessForWeather(i32 weather)
{
    switch (weather)
    {
        case 0: return PARAM_remixwet_clear.get_or(0.0f);
        case 1: return PARAM_remixwet_fog.get_or(0.0f);
        case 2: return PARAM_remixwet_rain.get_or(1.0f);
        case 3: return PARAM_remixwet_snow.get_or(0.35f);
        default: return 0.0f;
    }
}

static void ApplyGloss(f32 level)
{
    const f32 wet = PARAM_remixwet_gloss.get_or(0.45f);

    if (wet <= 0.0f)
        return;

    const f32 dry = PARAM_remixwet_dry_rough.get_or(0.7f);

    char value[32];
    std::snprintf(value, sizeof(value), "%.3f", dry + (wet - dry) * level);

    s_gloss_applied = agiDX9RemixApiSetConfig("rtx.legacyMaterial.roughnessConstant", value);
}

// Decides, once per race, whether the layer runs and at what level, and sets it up if so.
static void DecideRace()
{
    // No city has published its weather yet (a loading screen, a menu): undecided, not off, so the
    // race's first real ground draw decides.
    if (agiSkyEnv.Weather < 0)
        return;

    s_race = RaceState::Off;

    if (!PARAM_remixwet.get_or(true))
        return;

    const agiDX9RemixSceneApi* api = agiDX9RemixApiScene();

    if (!api)
        return;

    // Quantised, so that small edits to the per-weather values do not each mint a texture pair.
    s_level = std::round(std::clamp(WetnessForWeather(agiSkyEnv.Weather), 0.0f, 1.0f) * 20.0f) / 20.0f;

    if (s_level <= 0.0f)
        return;

    if (!PrepareTextures(s_level) || !CreateWetMaterial(*api, s_level))
        return;

    ApplyGloss(s_level);

    s_race = RaceState::On;
}

static Entry* FindOrInsert(u64 key, bool& inserted)
{
    inserted = false;

    for (u32 i = static_cast<u32>(key) & (kTableSize - 1);; i = (i + 1) & (kTableSize - 1))
    {
        Entry& entry = s_table[i];

        if (entry.State == EntryState::Free)
        {
            if (s_entries >= kMaxEntries)
                return nullptr;

            entry = {};
            entry.Key = key;
            inserted = true;
            return &entry;
        }

        if (entry.Key == key)
            return &entry;
    }
}

// Builds the wet twin of one road piece. False if it has nothing to lay a puddle on.
static bool BuildMesh(const agiDX9RemixSceneApi& api, Entry& entry, const agiWorldVtx* vertices, i32 vertex_count,
    const u16* indices, i32 index_count, const Matrix34& world)
{
    if ((static_cast<u32>(vertex_count) > kMaxSourceVertices) || (static_cast<u32>(index_count) > kMaxSourceIndices))
        return false;

    const f32 tile = std::max(PARAM_remixwet_tile.get_or(64.0f), 1.0f);
    const f32 slope = std::clamp(PARAM_remixwet_slope.get_or(0.8f), 0.0f, 1.0f);

    // Lifted clear of the road it covers. DECAL_STATIC asks Remix to treat the pair as a decal, and
    // the lift keeps the two surfaces from fighting over the same depth whatever the runtime does.
    constexpr f32 kLift = 0.005f;

    for (i32 i = 0; i < vertex_count; ++i)
        s_remap[i] = 0xFFFFFFFFu;

    u32 out_vertices = 0;
    u32 out_indices = 0;

    for (i32 tri = 0; (tri + 2) < index_count; tri += 3)
    {
        const u16 i0 = indices[tri];
        const u16 i1 = indices[tri + 1];
        const u16 i2 = indices[tri + 2];

        if ((i0 >= vertex_count) || (i1 >= vertex_count) || (i2 >= vertex_count))
            continue;

        Vector3 p0, p1, p2;
        p0.Dot(vertices[i0].pos, world);
        p1.Dot(vertices[i1].pos, world);
        p2.Dot(vertices[i2].pos, world);

        Vector3 normal;
        normal.Cross(p1 - p0, p2 - p0);

        const f32 length = std::sqrt(normal ^ normal);

        if (!(length > 1e-6f))
            continue;

        normal = normal * (1.0f / length);

        // Either winding: road pieces are not consistent about it, and the twin is double-sided.
        if (std::fabs(normal.y) < slope)
            continue;

        const Vector3 up = (normal.y < 0.0f) ? (normal * -1.0f) : normal;
        const u16 corners[3] {i0, i1, i2};
        const Vector3 positions[3] {p0, p1, p2};

        for (u32 k = 0; k < 3; ++k)
        {
            u32& slot = s_remap[corners[k]];

            if (slot == 0xFFFFFFFFu)
            {
                slot = out_vertices++;

                remixapi_HardcodedVertex& out = s_out_vertices[slot];
                out = {};
                out.position[0] = positions[k].x;
                out.position[1] = positions[k].y + kLift;
                out.position[2] = positions[k].z;
                out.normal[0] = up.x;
                out.normal[1] = up.y;
                out.normal[2] = up.z;
                out.texcoord[0] = positions[k].x / tile;
                out.texcoord[1] = positions[k].z / tile;
                out.color = 0xFFFFFFFFu;
            }

            s_out_indices[out_indices++] = slot;
        }
    }

    if (out_indices == 0)
        return false;

    remixapi_MeshInfoSurfaceTriangles surface {};
    surface.vertices_values = s_out_vertices;
    surface.vertices_count = out_vertices;
    surface.indices_values = s_out_indices;
    surface.indices_count = out_indices;
    surface.skinning_hasvalue = 0;
    surface.material = s_material;

    remixapi_MeshInfo info {};
    info.sType = REMIXAPI_STRUCT_TYPE_MESH_INFO;
    info.pNext = nullptr;
    info.hash = kMeshTag ^ (entry.Key & 0x00000000FFFFFFFFull) ^ ((entry.Key >> 32) << 16);
    info.surfaces_values = &surface;
    info.surfaces_count = 1;

    if (info.hash == 0)
        info.hash = kMeshTag;

    entry.Handle = nullptr;

    if ((api.CreateMesh(&info, &entry.Handle) != REMIXAPI_ERROR_CODE_SUCCESS) || !entry.Handle)
        return false;

    ++s_stats.Created;
    return true;
}

void agiDX9RemixWetBeginFrame()
{
    std::lock_guard<std::mutex> lock(s_lock);

    if (++s_frame == 0)
        s_frame = 1;

    s_created_this_frame = 0;
}

void agiDX9RemixWetGround(
    const agiWorldVtx* vertices, i32 vertex_count, const u16* indices, i32 index_count, const Matrix34& world)
{
    if (!vertices || !indices || (vertex_count <= 0) || (index_count < 3))
        return;

    std::lock_guard<std::mutex> lock(s_lock);

    if (s_race == RaceState::Unknown)
        DecideRace();

    if (s_race != RaceState::On)
        return;

    const agiDX9RemixSceneApi* api = agiDX9RemixApiScene();

    if (!api)
        return;

    u64 key = 0xCBF29CE484222325ull;
    key = Fnv(&world, sizeof(Matrix34), key);

    for (i32 i = 0; i < vertex_count; ++i)
        key = Fnv(&vertices[i].pos, sizeof(Vector3), key);

    key = Fnv(indices, static_cast<usize>(index_count) * sizeof(u16), key);

    if (key == 0)
        key = 1;

    bool inserted = false;
    Entry* entry = FindOrInsert(key, inserted);

    if (!entry)
    {
        ++s_stats.Skipped;
        return;
    }

    if (inserted)
    {
        if (s_created_this_frame >= static_cast<u32>(std::max(PARAM_remixwet_max_new.get_or(24), 1)))
        {
            // Over this frame's budget: give the slot back and pick the piece up next frame. Safe for
            // the probe chains, because the slot was free a moment ago and nothing was inserted since.
            *entry = {};
            ++s_stats.Skipped;
            return;
        }

        ++s_entries;
        ++s_created_this_frame;

        entry->State = BuildMesh(*api, *entry, vertices, vertex_count, indices, index_count, world) ? EntryState::Mesh
                                                                                                    : EntryState::Empty;
    }

    if ((entry->State != EntryState::Mesh) || (entry->LastFrame == s_frame))
        return;

    entry->LastFrame = s_frame;

    remixapi_InstanceInfo instance {};
    instance.sType = REMIXAPI_STRUCT_TYPE_INSTANCE_INFO;
    instance.pNext = nullptr;
    instance.categoryFlags = static_cast<remixapi_InstanceCategoryFlags>(REMIXAPI_INSTANCE_CATEGORY_BIT_DECAL_STATIC);
    instance.mesh = entry->Handle;
    instance.transform = {{{1.0f, 0.0f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 1.0f, 0.0f}}};
    instance.doubleSided = 1;

    if (api->DrawInstance(&instance) == REMIXAPI_ERROR_CODE_SUCCESS)
        ++s_stats.Drawn;
}

void agiDX9RemixWetEndGfx()
{
    std::lock_guard<std::mutex> lock(s_lock);

    if (const agiDX9RemixSceneApi* api = agiDX9RemixApiScene())
    {
        for (Entry& entry : s_table)
        {
            if ((entry.State == EntryState::Mesh) && entry.Handle)
                api->DestroyMesh(entry.Handle);
        }

        if (s_material)
            api->DestroyMaterial(s_material);
    }

    if (s_gloss_applied)
    {
        char value[32];
        std::snprintf(value, sizeof(value), "%.3f", PARAM_remixwet_dry_rough.get_or(0.7f));
        agiDX9RemixApiSetConfig("rtx.legacyMaterial.roughnessConstant", value);
    }

    for (Entry& entry : s_table)
        entry = {};

    s_entries = 0;
    s_material = nullptr;
    s_gloss_applied = false;
    s_race = RaceState::Unknown;
    s_level = 0.0f;
}

void agiDX9RemixWetLogStats(u32 frame)
{
    std::lock_guard<std::mutex> lock(s_lock);

    if (s_race != RaceState::On)
        return;

    Displayf("DX9 REMIXWET: frame=%u wetness=%.2f pieces=%u/%u | over 120 frames: created=%u drawn=%u skipped=%u",
        frame, s_level, s_entries, kMaxEntries, s_stats.Created, s_stats.Drawn, s_stats.Skipped);

    s_stats = {};
}
